AC_DEFUN([DUNE_STUFF_CHECKS],[
  DUNE_BOOST_BASE([1.48.0], [ DUNE_BOOST_FUSION ] , [] )
  
  AX_BOOST_FILESYSTEM
  AX_BOOST_DATE_TIME
  AX_BOOST_SYSTEM
  AX_BOOST_CHRONO
  AX_BOOST_TIMER
  AC_REQUIRE([GXX0X])
  AC_REQUIRE([LAMBDAS_CHECK])
  AC_REQUIRE([STD_BEGIN_END_CHECK])
])

AC_DEFUN([DUNE_STUFF_CHECK_MODULE],
[
    DUNE_CHECK_MODULES([dune-stuff], [stuff/exists.hh])
])
