# This file is part of the dune-stuff project:
#   https://github.com/wwu-numerik/dune-stuff
# Copyright holders: Rene Milk, Felix Schindler
# License: BSD 2-Clause License (http://opensource.org/licenses/BSD-2-Clause)

Module:dune-stuff
Version:2.3.0
Maintainer:rene.milk@uni-muenster.de
Depends: dune-xt-common dune-common (>= 2.4) dune-geometry (>= 2.4) dune-testtools (>= 2.4)
Suggests: dune-grid (> 2.2) dune-fem (> 1.3) dune-istl (> 2.2) dune-pdelab dune-typetree dune-alugrid
