#ifndef DUNE_STUFF_FEM_NAMESPACE_HH
#define DUNE_STUFF_FEM_NAMESPACE_HH

#include <config.h>
#include <dune/common/version.hh>

#ifdef HAVE_DUNE_FEM

#if DUNE_VERSION_EQUAL_REV(DUNE_FEM,1,4,-1)
  #define DUNE_FEM_IS_LOCALFUNCTIONS_COMPATIBLE 1
  #define DUNE_FEM_IS_MULTISCALE_COMPATIBLE 0
#elif DUNE_VERSION_EQUAL_REV(DUNE_FEM,1,4,-2)
  #define DUNE_FEM_IS_MULTISCALE_COMPATIBLE 1
  #define DUNE_FEM_IS_LOCALFUNCTIONS_COMPATIBLE 0
#endif

#endif // HAVE_DUNE_FEM

#endif // DUNE_STUFF_FEM_NAMESPACE_HH
